export const Path = {
  HOME: "/*",
  LOGIN: "login",
  REGISTER: "register",
  CHO_THUE_CAN_HO: "cho-thue-can-ho",
  CHO_THUE_MAT_BANG: "cho-thue-mat-bang",
  CHO_THUE_PHONG_TRO: "cho-thue-phong-tro",
  NHA_CHO_THUE: "nha-cho-thue",
  DETAIL_POST: "chi-tiet/:title/:postId",
  DETAIL: "/chi-tiet/",
  DETAIL_ALL: "chi-tiet/*",
  SYSTEM: "/he-thong/*",
  CREATE_POST: "tao-tin-cho-thue",
  MANAGER_POST: "quan-ly-tin-dang",
  INFO_USER: "thong-tin-ca-nhan",
};
