const actionTypes = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIl: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAIL: "GET_CATEGORY_FAIL",
  GET_ALL_POST_SUCCESS: "GET_ALL_POST_SUCCESS",
  GET_ALL_POST_FAIL: "GET_ALL_POST_FAIL",
  GET_POST_BY_LIMIT_SUCCESS: "GET_POST_BY_LIMIT_SUCCESS",
  GET_POST_BY_LIMIT_FAIL: "GET_POST_BY_LIMIT_FAIL",
  GET_FILTER_PRICE_SUCCESS: "GET_FILTER_PRICE_SUCCESS",
  GET_FILTER_PRICE_FAIL: "GET_FILTER_PRICE_FAIL",
  GET_FILTER_ACREAGE_SUCCESS: "GET_FILTER_ACREAGE_SUCCESS",
  GET_FILTER_ACREAGE_FAIL: "GET_FILTER_ACREAGE_FAIL",
  GET_NEWS_POST_SUCCESS: "GET_NEWS_POST_SUCCESS",
  GET_NEWS_POST_FAIL: "GET_NEWS_POST_FAIL",
  GET_LIST_PROVINCE_SUCCESS: "GET_LIST_PROVINCE_SUCCESS",
  GET_LIST_PROVINCE_FAIL: "GET_LIST_PROVINCE_FAIL",
};

export default actionTypes;
