const actionTypes = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIl: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAIL: "GET_CATEGORY_FAIL",
  GET_ALL_POST_SUCCESS: "GET_ALL_POST_SUCCESS",
  GET_ALL_POST_FAIL: "GET_ALL_POST_FAIL",
  GET_POST_BY_LIMIT_SUCCESS: "GET_POST_BY_LIMIT_SUCCESS",
  GET_POST_BY_LIMIT_FAIL: "GET_POST_BY_LIMIT_FAIL",
};

export default actionTypes;
